name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  backend:
    name: Backend (lint + test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint
        run: npm run lint

      - name: Test
        env:
          NODE_ENV: test
        run: npm test

  frontend:
    name: Frontend (build)
    runs-on: ubuntu-latest
    env:
      ROLLUP_SKIP_NODEJS_NATIVE: "1"
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean lockfile and modules (workaround npm optional deps bug)
        run: rm -f package-lock.json && rm -rf node_modules

      - name: Install dependencies (no lockfile)
        run: npm install --no-audit --no-fund

      - name: Show rollup version
        run: npx rollup --version || node -e "console.log(require('rollup/package.json').version)"

      - name: Build
        run: npm run build
